name: Release
on:
    push:
        branches:
            - main
jobs:
    test:
        name: Test & Build on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: [16]
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macOS-latest
                include:
                    - node: 14
                      os: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - name: Lint
              run: make lint
            - name: Verify build succeeds
              run: make prepack

    release:
        name: Release
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install dependencies
              run: make node_modules
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm exec semantic-release
